name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Publish Dart/Flutter package - latest flutter
        uses: afonsocraposo/actions-flutter-pub-publisher@v1.1.0
        with:
          # Set this secret in your repository settings: Settings > Secrets
          credential: ${{ secrets.GOOGLE_CREDENTIALS }}
          flutter_package: true
          skip_test: false
          package_directory: '.'
          dry_run: true

      - name: Run Analyzer
        run: flutter analyze

      - name: Run Tests
        run: flutter test
